language: node_js
node_js:
  - "7"
install:
    - npm install
notifications:
    email:
        - vlpetrovic99@gmail.com
        - g.geneva94@gmail.com
    on_success: never
    on_failure: always
before_deploy:
    - npm install
    - npm test
